// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model



type NewCompany struct {
	CompanyName string `json:"companyName"`
	FoundedYear string `json:"foundedYear"`
	Location    string `json:"location"`
	Address     string `json:"address"`
	UserID      string `json:"userId"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}



type UserSignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
